"""add post.body_html in post

Revision ID: 00f07e0ed6bb
Revises: 4e5f183fdb1e
Create Date: 2017-03-29 16:37:06.252362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00f07e0ed6bb'
down_revision = '4e5f183fdb1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
